const dataInfo = {
  "Ba Đình": [
    "Phúc Xá",
    "Trúc Bạch",
    "Vĩnh Phúc",
    "Cống Vị",
    "Liễu Giai",
    "Ngọc Hà",
    "Điện Biên",
    "Đội Cấn",
    "Ngọc Khánh",
    "Kim Mã",
    "Giảng Võ",
    "Thành Công",
    "Phúc Tân"
  ],
  "Hoàn Kiếm": [
    "Phúc Tân",
    "Đồng Xuân",
    "Cửa Đông",
    "Lý Thái Tổ",
    "Hàng Bạc",
    "Hàng Buồm",
    "Hàng Đào",
    "Hàng Gai",
    "Cửa Nam",
    "Hàng Bồ",
    "Hàng Bông",
    "Tràng Tiền",
    "Hàng Trống",
    "Hàng Bài"
  ],
  "Hai Bà Trưng": [
    "Nguyễn Du",
    "Bùi Thị Xuân",
    "Bạch Đằng",
    "Phạm Đình Hổ",
    "Ngô Thì Nhậm",
    "Nguyễn Gia Thiều",
    "Lê Đại Hành",
    "Nguyễn Bỉnh Khiêm",
    "Lê Quý Đôn",
    "Quỳnh Lôi",
    "Vĩnh Tuy",
    "Bách Khoa",
    "Đồng Nhân"
  ],
  "Đống Đa": [
    "Cát Linh",
    "Quốc Tử Giám",
    "Văn Miếu",
    "Hàng Bột",
    "Láng Thượng",
    "Láng Hạ",
    "Láng Thanh",
    "O Cho Dua",
    "Trung Phụng",
    "Quang Trung",
    "Trung Liệt",
    "Phương Liên",
    "Thịnh Quang",
    "Trung Tự"
  ],
  "Tây Hồ": [
    "Phú Thượng",
    "Nhật Tân",
    "Tứ Liên",
    "Quảng An",
    "Xuân La",
    "Yên Phụ",
    "Bưởi",
    "Thụy Khuê",
    "Thụy Khuê",
    "Xuân La",
    "Tây Hồ",
    "Phú Thượng"
  ],
  "Cầu Giấy": [
    "Nghĩa Đô",
    "Nghĩa Tân",
    "Mai Dịch",
    "Dịch Vọng",
    "Dịch Vọng Hậu",
    "Quan Hoa",
    "Yên Hoà",
    "Trung Hoà",
    "Nghĩa Đô",
    "Nghĩa Tân"
  ],
  "Thanh Xuân": [
    "Khương Trung",
    "Khương Mai",
    "Khương Đình",
    "Thanh Xuân Trung",
    "Phương Liệt",
    "Thanh Xuân Bắc",
    "Nhân Chính",
    "Thanh Xuân Nam",
    "Hạ Đình"
  ],
  "Hoàng Mai": [
    "Hoàng Văn Thụ",
    "Giáp Bát",
    "Thanh Trì",
    "Vĩnh Hưng",
    "Định Công",
    "Trường Thịnh",
    "Yên Sở",
    "Tân Mai",
    "Thịnh Liệt",
    "Hoàng Liệt"
  ],
  "Long Biên": [
    "Gia Thụy",
    "Ngọc Lâm",
    "Ngọc Thụy",
    "Phúc Đồng",
    "Sài Đồng",
    "Bồ Đề",
    "Cự Khối",
    "Thạch Bàn",
    "Việt Hưng",
    "Bạch Đằng",
    "Long Biên"
  ],
  "Nam Từ Liêm": [
    "Cầu Diễn",
    "Phú Diễn",
    "Xuân Phương",
    "Mễ Trì",
    "Mỹ Đình 1",
    "Mỹ Đình 2",
    "Tây Mỗ",
    "Trung Văn",
    "Đại Mỗ",
    "Đồng Ngạc"
  ],
  "Bắc Từ Liêm": [
    "Thượng Cát",
    "Liên Mạc",
    "Đông Ngạc",
    "Đức Thắng",
    "Thụy Phương",
    "Tây Tựu",
    "Xuân Đỉnh",
    "Minh Khai",
    "Cổ Nhuế",
    "Phúc Diễn"
  ],
  "Thanh Trì": [
    "Vĩnh Quỳnh",
    "Ngũ Hiệp",
    "Tả Thanh Oai",
    "Hữu Hòa",
    "Tam Hiệp",
    "Tứ Hiệp",
    "Yên Mỹ",
    "Tân Triều",
    "Đông Mỹ"
  ],
  "Gia Lâm": [
    "Trâu Quỳ",
    "Yên Viên",
    "Yên Thường",
    "Yên Viên",
    "Đa Tốn",
    "Kim Sơn",
    "Dương Hà",
    "Phù Đổng",
    "Ninh Hiệp"
  ],
  "Đông Anh": [
    "Phú Lãm",
    "Kim Chung",
    "Đại Mạch",
    "Vân Hà",
    "Uy Nỗ",
    "Võng La",
    "Tàm Xá",
    "Mai Lâm",
    "Tiên Dương"
  ],
  "Sóc Sơn": [
    "Quang Tiến",
    "Việt Long",
    "Hồng Kỳ",
    "Minh Phú",
    "Phù Linh",
    "Bắc Sơn",
    "Tân Minh",
    "Quang Minh",
    "Việt Hùng"
  ],
  "Mê Linh": [
    "Mê Linh",
    "Chi Đông",
    "Quang Minh",
    "Tam Đồng",
    "Thanh Lâm",
    "Tiền Phong",
    "Tiến Thắng",
    "Tiến Thịnh"
  ],
  "Hà Đông": [
    "Mộ Lao",
    "Văn Quán",
    "Vạn Phúc",
    "Yết Kiêu",
    "Quang Trung",
    "Dương Nội",
    "La Khê",
    "Yên Nghĩa",
    "Kiến Hưng",
    "Hà Cầu",
    "Vạn Yên"
  ]
};
