name: ecommerce_flutter
description: "A new Flutter project."

# flutter pub run build_runner build --delete-conflicting-outputs
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  dio: 5.4.1
  flutter_bloc: 8.1.5
  auto_route: 5.0.4
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  logger: 2.1.0
  json_serializable: 6.7.1
  shared_preferences: 2.2.2
  image_network: 2.5.6
  jwt_decoder: 2.0.1
  dart_jsonwebtoken: 2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.8
  auto_route_generator: 5.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
